version: 2

models:
  - name: public_orders
    description: "Public orders model exposed for cross-project consumption"
    access: public
    config:
      contract:
        enforced: true
    columns:
      - name: order_id
        description: "Unique order identifier"
        data_type: integer
        constraints:
          - type: not_null
      - name: status
        description: "Order status (PENDING, COMPLETED, SHIPPED)"
        data_type: varchar
      - name: amount
        description: "Order total amount"
        data_type: "decimal(10,2)"
      - name: created_at
        description: "Order creation timestamp"
        data_type: "timestamp_ntz"
